In [1]:
import numpy as np

In [37]:
pts = np.array([[0, 0], [0, 500], [500, 500], [500, 0]])
pts

array([[  0,   0],
       [  0, 500],
       [500, 500],
       [500,   0]])

In [33]:
rect = np.zeros((4, 2), dtype="float32")
rect

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [38]:
s = pts.sum(axis=1)
s

array([   0,  500, 1000,  500])

In [39]:
rect[0] = pts[np.argmin(s)]
rect[0]

array([0., 0.], dtype=float32)

In [40]:
rect[2] = pts[np.argmax(s)]
rect[2]

array([500., 500.], dtype=float32)

In [42]:
diff = np.diff(pts, axis=1)
diff

array([[   0],
       [ 500],
       [   0],
       [-500]])

In [43]:
	rect[1] = pts[np.argmin(diff)]
	rect[3] = pts[np.argmax(diff)]

In [44]:
rect

array([[  0.,   0.],
       [500.,   0.],
       [500., 500.],
       [  0., 500.]], dtype=float32)

In [45]:
from scipy.spatial import distance as dist 

In [46]:
xSorted = pts[np.argsort(pts[:, 0]), :]
xSorted

array([[  0,   0],
       [  0, 500],
       [500, 500],
       [500,   0]])

In [50]:
	leftMost = xSorted[:2, :]
	rightMost = xSorted[2:, :]

In [51]:
leftMost = leftMost[np.argsort(leftMost[:, 1]), :]
leftMost

array([[  0,   0],
       [  0, 500]])

In [52]:
(tl, bl) = leftMost

In [54]:
D = dist.cdist(tl[np.newaxis], rightMost, "euclidean")[0]
(br, tr) = rightMost[np.argsort(D)[::-1], :]
D    

array([707.10678119, 500.        ])

In [55]:
main_rect = np.array([tl, tr, br, bl], dtype="float32")
main_rect

array([[  0.,   0.],
       [500.,   0.],
       [500., 500.],
       [  0., 500.]], dtype=float32)

In [56]:
np.array([tl, tr, br, bl], dtype="float32")

array([[  0.,   0.],
       [500.,   0.],
       [500., 500.],
       [  0., 500.]], dtype=float32)

In [57]:
br

array([500, 500])

In [58]:
tr

array([500,   0])